export const GET_INVOICES = "GET_INVOICES";
export const GET_INVOICES_LOADING = "GET_INVOICES_LOADING";
export const ADD_INVOICE_REQ = "ADD_INVOICE_REQ";
export const ADD_INVOICE_SUCCESS = "ADD_INVOICE_SUCCESS";
export const ADD_INVOICE_FAILURE = "ADD_INVOICE_FAILURE";
export const CHANGE_TEMPLATE = "CHANGE_TEMPLATE";
